-- ============================================================
-- ノボル Supabase スキーマ（v2）
-- 仕様は docs/spec.md を参照
-- Supabase の「SQL Editor」に貼り付けて実行してください（Storage バケットも作成されます）
-- （旧 supabase_schema.sql とは互換性がありません。新しいプロジェクトに適用する想定）
-- ============================================================

-- ─── 列挙型 ─────────────────────────────────────────────────
CREATE TYPE parking_status AS ENUM ('dedicated', 'nearby', 'none', 'unknown');
-- 御朱印: direct_only=直書きのみ / written_only=書き置きのみ / both=直書き・書き置き / available=あり（種類は不明。旧データ）
CREATE TYPE goshuin_status AS ENUM ('available', 'written_only', 'none', 'unknown', 'direct_only', 'both');
CREATE TYPE shrine_status  AS ENUM ('active', 'hidden');
CREATE TYPE request_status AS ENUM ('pending', 'approved', 'rejected');

-- ============================================================
-- 1. 神社マスタ
--    元データは OSM / Wikidata / Wikipedia（scripts/ の取り込み処理で投入）
--    ユーザーは直接更新できず、shrine_edits 経由でのみ変更される
-- ============================================================
CREATE TABLE shrines (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 数値IDは一覧ファイルを小さくするため
  osm_ref             TEXT UNIQUE,              -- 'node/123' 'way/456' など。申請で追加された社は NULL
  wikidata_id         TEXT,                     -- 'Q123456'
  name                TEXT NOT NULL,            -- 名前のない祠は「名称不明の社（地名）」
  name_kana           TEXT,
  prefecture          TEXT NOT NULL,
  municipality        TEXT,
  locality            TEXT,                     -- 近くの地名（町・字など）。同じ名前の神社を見分ける用
  address             TEXT,
  lat                 DOUBLE PRECISION NOT NULL,
  lng                 DOUBLE PRECISION NOT NULL,

  -- 基本情報
  deities             TEXT,                     -- ご祭神
  benefits            TEXT[] NOT NULL DEFAULT '{}',  -- ご利益
  shrine_rank         TEXT,                     -- 社格
  founded             TEXT,                     -- 創建（「伝・景行天皇の御代」のように書くことが多いので文字で）
  annual_festival     TEXT,                     -- 例祭（「毎年9月15日」など）
  visiting_hours      TEXT,                     -- 拝観時間
  highlights          TEXT,                     -- 見どころ

  -- アクセス（駅・バス停は取り込み時に OSM から自動計算。情報提供されたら *_by_user = TRUE にして以後は上書きしない）
  nearest_station          TEXT,
  nearest_station_m        INTEGER,             -- 直線距離（m）。情報提供された駅は NULL
  nearest_station_by_user  BOOLEAN NOT NULL DEFAULT FALSE,
  nearest_bus_stop         TEXT,
  nearest_bus_stop_m       INTEGER,
  nearest_bus_stop_by_user BOOLEAN NOT NULL DEFAULT FALSE,
  access_note              TEXT,                -- 「〇〇駅から徒歩15分、石段あり」など補足
  parking             parking_status NOT NULL DEFAULT 'unknown',
  goshuin             goshuin_status NOT NULL DEFAULT 'unknown',
  goshuin_note        TEXT,                     -- 「授与は9時〜16時」「限定御朱印あり」など

  -- 由緒（神話・創建の背景など。画面では「由緒」）
  features            TEXT,
  features_source     TEXT,                     -- 'wikipedia:<記事名>' / 'user' / 'editor'

  -- 集計（records のトリガーで自動更新）
  record_count        INTEGER NOT NULL DEFAULT 0,
  visitor_count       INTEGER NOT NULL DEFAULT 0,   -- 参拝したユーザー数（重複なし）
  first_visited_on    DATE,                        -- 最初の参拝日。NULL = まだ誰も行っていない
  stats_updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),  -- 集計列の更新時刻（端末の差分取得用）

  status              shrine_status NOT NULL DEFAULT 'active',
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_shrines_prefecture ON shrines(prefecture);
CREATE INDEX idx_shrines_latlng     ON shrines(lat, lng);
CREATE INDEX idx_shrines_stats_upd ON shrines(stats_updated_at);
CREATE INDEX idx_shrines_unvisited  ON shrines(prefecture) WHERE first_visited_on IS NULL AND status = 'active';

-- ============================================================
-- 2. 参拝記録
-- ============================================================
CREATE TABLE records (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),  -- 端末側で採番して送る（オフライン再送で二重登録しないため）
  user_id             UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  shrine_id           BIGINT NOT NULL REFERENCES shrines(id) ON DELETE RESTRICT,
  visited_on          DATE NOT NULL DEFAULT CURRENT_DATE,   -- 後から選べる
  emotion_level       INTEGER NOT NULL DEFAULT 50 CHECK (emotion_level BETWEEN 0 AND 100),
  public_memo         TEXT NOT NULL DEFAULT '',
  is_public           BOOLEAN NOT NULL DEFAULT TRUE,
  onsite              BOOLEAN NOT NULL DEFAULT FALSE,       -- 「現地で記録」印（GPSで近くにいた）
  location_accuracy_m INTEGER,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_records_user   ON records(user_id, visited_on DESC);
CREATE INDEX idx_records_shrine ON records(shrine_id, visited_on DESC);
CREATE INDEX idx_records_public_timeline ON records(visited_on DESC, created_at DESC) WHERE is_public;  -- みんなの参拝

-- 非公開メモは別テーブル（records を公開しても読まれないように）
CREATE TABLE record_private_notes (
  record_id    UUID PRIMARY KEY REFERENCES records(id) ON DELETE CASCADE,
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  private_memo TEXT NOT NULL DEFAULT ''
);

-- 写真（Storage バケット 'photos' に保存。パスは <record_id>/<n>.jpg。user_id を含めない）
CREATE TABLE photos (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  record_id  UUID NOT NULL REFERENCES records(id) ON DELETE CASCADE,
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  path       TEXT NOT NULL UNIQUE,
  tag        TEXT NOT NULL DEFAULT 'other'      -- 写っているもの。神社詳細でタグごとに見られる
             CHECK (tag IN ('torii', 'komainu', 'honden', 'goshuin', 'signboard', 'other')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_photos_record ON photos(record_id);

-- ============================================================
-- 3. 情報提供（神社情報の追加・訂正）
--    「最後に提供された内容をすぐ採用し、履歴を残す」方式。いたずらは管理者が元に戻す
-- ============================================================
CREATE TABLE shrine_edits (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shrine_id  BIGINT NOT NULL REFERENCES shrines(id) ON DELETE CASCADE,
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  field      TEXT NOT NULL CHECK (field IN (
               'address', 'deities', 'benefits', 'shrine_rank',
               'access_note', 'parking', 'goshuin', 'features', 'name_kana',
               'goshuin_note', 'nearest_station', 'nearest_bus_stop',
               'founded', 'annual_festival', 'visiting_hours', 'highlights')),
  value      JSONB NOT NULL,                    -- 文字列 / 文字列配列 / 列挙値
  old_value  JSONB,                             -- 変更前の値（{列名: 値}）。トリガーが入れる。管理者が元に戻すときに使う
  reverted_at TIMESTAMPTZ,                      -- 管理者が元に戻した時刻
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_shrine_edits_shrine  ON shrine_edits(shrine_id, created_at DESC);
CREATE INDEX idx_shrine_edits_created ON shrine_edits(created_at DESC);
CREATE INDEX idx_shrine_edits_user    ON shrine_edits(user_id, created_at DESC);

-- 管理者が確認する申請
--   add  : リストにない神社の追加（管理者が確認して shrines に追加）
--   hide : 境内社・重複・現存しないなど、一覧から外すべき神社の報告（確認して status = 'hidden'）
CREATE TABLE shrine_requests (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  kind       TEXT NOT NULL DEFAULT 'add' CHECK (kind IN ('add', 'hide')),
  shrine_id  BIGINT REFERENCES shrines(id) ON DELETE CASCADE,   -- hide のとき対象
  name       TEXT NOT NULL,
  lat        DOUBLE PRECISION,
  lng        DOUBLE PRECISION,
  note       TEXT NOT NULL DEFAULT '',
  from_map   BOOLEAN NOT NULL DEFAULT FALSE,                    -- 「記録する」の地図でピンを立てて申請（現地にいた）
  status     request_status NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ                                        -- 承認・却下した時刻
);

-- 管理者（申請の承認・却下と神社一覧ファイルの作り直しができる）
-- 登録は SQL Editor から: INSERT INTO admins (user_id) SELECT id FROM auth.users WHERE email = '<メールアドレス>';
CREATE TABLE admins (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE
);

-- 情報提供・申請を止めたユーザー（管理者が「情報提供の確認」画面から登録）
CREATE TABLE banned_editors (
  user_id    UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- アプリへのご意見・ご要望（管理者だけが読める）
CREATE TABLE feedback (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  screen     TEXT NOT NULL CHECK (screen IN ('nearby', 'record', 'shrine', 'map', 'search', 'community', 'records', 'profile', 'other')),  -- どの画面について
  body       TEXT NOT NULL CHECK (char_length(btrim(body)) BETWEEN 1 AND 2000),
  done_at    TIMESTAMPTZ,                       -- 管理者が「対応済み」にした時刻
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_feedback_created ON feedback(created_at DESC);

-- ニックネーム。「名前を出す」にした人だけ、公開記録・情報提供者の一覧に名前が載る
-- 本人と管理者だけが読める。ほかの人には下の読み取り用の関数を通して名前だけを返す
CREATE TABLE profiles (
  user_id    UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nickname   TEXT CHECK (nickname IS NULL OR (
               nickname = btrim(nickname) AND char_length(nickname) BETWEEN 1 AND 20 AND nickname !~ '[[:cntrl:]]')),
  show_name  BOOLEAN NOT NULL DEFAULT FALSE,   -- 「名前を出す」
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 同じニックネーム（大文字・小文字の違いを含む）は1人だけ
CREATE UNIQUE INDEX idx_profiles_nickname ON profiles (lower(nickname)) WHERE nickname IS NOT NULL;

-- 神社でお祈りしたいこと（マイページの自由記述。本人だけが読み書きできる。管理者も読めない）
CREATE TABLE prayers (
  user_id    UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  body       TEXT NOT NULL DEFAULT '' CHECK (char_length(body) <= 1000),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 4. 参拝の手引き（note 記事へのリンク）
--    context: 'general'=マイページ一覧 / 'etiquette'=記録画面 / 'goshuin'=御朱印欄 など
-- ============================================================
CREATE TABLE guide_links (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title       TEXT NOT NULL,
  url         TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  context     TEXT NOT NULL DEFAULT 'general',
  sort_order  INTEGER NOT NULL DEFAULT 0,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE
);

-- ============================================================
-- 5. アプリ設定値（神社一覧ファイルのバージョンなど）
-- ============================================================
CREATE TABLE app_meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

INSERT INTO app_meta (key, value) VALUES ('shrine_index_version', '0');

-- ============================================================
-- トリガー
-- ============================================================

-- records の増減で shrines の集計列を更新
CREATE OR REPLACE FUNCTION refresh_shrine_stats(target BIGINT) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  UPDATE shrines s SET
    record_count     = agg.cnt,
    visitor_count    = agg.users,
    first_visited_on = agg.first_on,
    stats_updated_at = NOW()
  FROM (
    SELECT COUNT(*)::INT AS cnt,
           COUNT(DISTINCT user_id)::INT AS users,
           MIN(visited_on) AS first_on
    FROM records WHERE shrine_id = target
  ) agg
  WHERE s.id = target;
END $$;

CREATE OR REPLACE FUNCTION on_record_change() RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF TG_OP IN ('INSERT', 'UPDATE') THEN
    PERFORM refresh_shrine_stats(NEW.shrine_id);
  END IF;
  IF TG_OP IN ('DELETE', 'UPDATE') AND (TG_OP = 'DELETE' OR OLD.shrine_id <> NEW.shrine_id) THEN
    PERFORM refresh_shrine_stats(OLD.shrine_id);
  END IF;
  RETURN NULL;
END $$;

CREATE TRIGGER trg_records_stats
AFTER INSERT OR UPDATE OF shrine_id, visited_on, user_id OR DELETE ON records
FOR EACH ROW EXECUTE FUNCTION on_record_change();

-- 項目ごとに、変更で書き換わる shrines の列
CREATE OR REPLACE FUNCTION shrine_edit_columns(field TEXT) RETURNS TEXT[]
LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE field
    WHEN 'features'         THEN ARRAY['features', 'features_source']
    WHEN 'nearest_station'  THEN ARRAY['nearest_station', 'nearest_station_m', 'nearest_station_by_user']
    WHEN 'nearest_bus_stop' THEN ARRAY['nearest_bus_stop', 'nearest_bus_stop_m', 'nearest_bus_stop_by_user']
    ELSE ARRAY[field]
  END;
$$;

-- 情報提供を shrines に反映（最後に提供された内容を採用）。変更前の値を old_value に残す
CREATE OR REPLACE FUNCTION apply_shrine_edit() RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  txt TEXT := NULLIF(btrim(NEW.value #>> '{}'), '');   -- 文字列の項目。空なら NULL に戻す
BEGIN
  NEW.reverted_at := NULL;
  SELECT jsonb_object_agg(e.key, e.value) INTO NEW.old_value
  FROM shrines s, jsonb_each(to_jsonb(s)) AS e
  WHERE s.id = NEW.shrine_id AND e.key = ANY(shrine_edit_columns(NEW.field));

  UPDATE shrines SET
    address         = CASE WHEN NEW.field = 'address'      THEN txt ELSE address END,
    name_kana       = CASE WHEN NEW.field = 'name_kana'    THEN txt ELSE name_kana END,
    deities         = CASE WHEN NEW.field = 'deities'      THEN txt ELSE deities END,
    shrine_rank     = CASE WHEN NEW.field = 'shrine_rank'  THEN txt ELSE shrine_rank END,
    access_note     = CASE WHEN NEW.field = 'access_note'  THEN txt ELSE access_note END,
    goshuin_note    = CASE WHEN NEW.field = 'goshuin_note' THEN txt ELSE goshuin_note END,
    founded         = CASE WHEN NEW.field = 'founded'         THEN txt ELSE founded END,
    annual_festival = CASE WHEN NEW.field = 'annual_festival' THEN txt ELSE annual_festival END,
    visiting_hours  = CASE WHEN NEW.field = 'visiting_hours'  THEN txt ELSE visiting_hours END,
    highlights      = CASE WHEN NEW.field = 'highlights'      THEN txt ELSE highlights END,
    features        = CASE WHEN NEW.field = 'features'     THEN txt ELSE features END,
    features_source = CASE WHEN NEW.field = 'features'     THEN 'user' ELSE features_source END,
    benefits        = CASE WHEN NEW.field = 'benefits'
                        THEN ARRAY(SELECT jsonb_array_elements_text(NEW.value)) ELSE benefits END,
    parking         = CASE WHEN NEW.field = 'parking' THEN (NEW.value #>> '{}')::parking_status ELSE parking END,
    goshuin         = CASE WHEN NEW.field = 'goshuin' THEN (NEW.value #>> '{}')::goshuin_status ELSE goshuin END,
    -- 駅・バス停：提供された文字（「〇〇駅 徒歩10分」など）をそのまま表示する。空にしたら次の取り込みで OSM の値に戻る
    nearest_station         = CASE WHEN NEW.field = 'nearest_station' THEN txt ELSE nearest_station END,
    nearest_station_m       = CASE WHEN NEW.field = 'nearest_station' THEN NULL ELSE nearest_station_m END,
    nearest_station_by_user = CASE WHEN NEW.field = 'nearest_station' THEN txt IS NOT NULL ELSE nearest_station_by_user END,
    nearest_bus_stop         = CASE WHEN NEW.field = 'nearest_bus_stop' THEN txt ELSE nearest_bus_stop END,
    nearest_bus_stop_m       = CASE WHEN NEW.field = 'nearest_bus_stop' THEN NULL ELSE nearest_bus_stop_m END,
    nearest_bus_stop_by_user = CASE WHEN NEW.field = 'nearest_bus_stop' THEN txt IS NOT NULL ELSE nearest_bus_stop_by_user END,
    updated_at      = NOW()
  WHERE id = NEW.shrine_id;
  RETURN NEW;
END $$;

-- 変更前の値を残すため、追加の前に反映する
CREATE TRIGGER trg_shrine_edits_apply
BEFORE INSERT ON shrine_edits
FOR EACH ROW EXECUTE FUNCTION apply_shrine_edit();

-- ============================================================
-- 集計関数（個人を特定しない数字だけを返す）
-- ============================================================

-- ホームに出す全体の数字
-- recent_visitors: 過去30日（今日を含む）に1社以上参拝したユーザー数
CREATE OR REPLACE FUNCTION get_app_stats() RETURNS JSON
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT json_build_object(
    'recent_visitors', (SELECT COUNT(DISTINCT user_id) FROM records
                         WHERE visited_on BETWEEN CURRENT_DATE - 29 AND CURRENT_DATE),
    'total_shrines',   (SELECT COUNT(*) FROM shrines WHERE status = 'active'),
    'visited_shrines', (SELECT COUNT(*) FROM shrines
                         WHERE status = 'active' AND first_visited_on IS NOT NULL)
  );
$$;

-- 都道府県別の達成率
CREATE OR REPLACE FUNCTION get_prefecture_progress() RETURNS TABLE (
  prefecture TEXT, total BIGINT, visited BIGINT
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT prefecture,
         COUNT(*),
         COUNT(*) FILTER (WHERE first_visited_on IS NOT NULL)
  FROM shrines WHERE status = 'active'
  GROUP BY prefecture ORDER BY prefecture;
$$;

GRANT EXECUTE ON FUNCTION get_app_stats(), get_prefecture_progress() TO anon, authenticated;
REVOKE EXECUTE ON FUNCTION refresh_shrine_stats(BIGINT) FROM PUBLIC, anon, authenticated;

-- ============================================================
-- 取り込み処理用（scripts/import-shrines.mjs から service_role で呼ぶ）
--   OSM 由来の列は毎回上書き。ユーザーが情報提供できる列は「空のときだけ」埋める
--   駅・バス停は情報提供されたもの（*_by_user）を上書きしない
-- ============================================================
CREATE OR REPLACE FUNCTION import_shrines(rows JSONB) RETURNS INTEGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE n INTEGER;
BEGIN
  INSERT INTO shrines AS s (
    osm_ref, wikidata_id, name, name_kana, prefecture, municipality, locality, address, lat, lng,
    deities, benefits, shrine_rank, nearest_station, nearest_station_m,
    nearest_bus_stop, nearest_bus_stop_m, parking, features, features_source
  )
  SELECT r.osm_ref, r.wikidata_id, r.name, r.name_kana, r.prefecture, r.municipality, r.locality, r.address, r.lat, r.lng,
         r.deities, COALESCE(r.benefits, '{}'), r.shrine_rank, r.nearest_station, r.nearest_station_m,
         r.nearest_bus_stop, r.nearest_bus_stop_m, COALESCE(r.parking, 'unknown'), r.features, r.features_source
  FROM jsonb_to_recordset(rows) AS r(
    osm_ref TEXT, wikidata_id TEXT, name TEXT, name_kana TEXT, prefecture TEXT, municipality TEXT, locality TEXT,
    address TEXT, lat DOUBLE PRECISION, lng DOUBLE PRECISION, deities TEXT, benefits TEXT[],
    shrine_rank TEXT, nearest_station TEXT, nearest_station_m INTEGER, nearest_bus_stop TEXT,
    nearest_bus_stop_m INTEGER, parking parking_status, features TEXT, features_source TEXT)
  ON CONFLICT (osm_ref) DO UPDATE SET
    wikidata_id        = EXCLUDED.wikidata_id,
    name               = EXCLUDED.name,
    prefecture         = EXCLUDED.prefecture,
    municipality       = EXCLUDED.municipality,
    locality           = EXCLUDED.locality,
    lat                = EXCLUDED.lat,
    lng                = EXCLUDED.lng,
    -- 駅・バス停を取らずに取り込んだとき（--shrines-only / --no-transit）は、入っている値を消さない
    nearest_station    = CASE WHEN s.nearest_station_by_user  OR EXCLUDED.nearest_station  IS NULL THEN s.nearest_station    ELSE EXCLUDED.nearest_station END,
    nearest_station_m  = CASE WHEN s.nearest_station_by_user  OR EXCLUDED.nearest_station  IS NULL THEN s.nearest_station_m  ELSE EXCLUDED.nearest_station_m END,
    nearest_bus_stop   = CASE WHEN s.nearest_bus_stop_by_user OR EXCLUDED.nearest_bus_stop IS NULL THEN s.nearest_bus_stop   ELSE EXCLUDED.nearest_bus_stop END,
    nearest_bus_stop_m = CASE WHEN s.nearest_bus_stop_by_user OR EXCLUDED.nearest_bus_stop IS NULL THEN s.nearest_bus_stop_m ELSE EXCLUDED.nearest_bus_stop_m END,
    name_kana          = COALESCE(s.name_kana,   EXCLUDED.name_kana),
    address            = COALESCE(s.address,     EXCLUDED.address),
    deities            = COALESCE(s.deities,     EXCLUDED.deities),
    shrine_rank        = COALESCE(s.shrine_rank, EXCLUDED.shrine_rank),
    benefits           = CASE WHEN cardinality(s.benefits) = 0 THEN EXCLUDED.benefits ELSE s.benefits END,
    parking            = CASE WHEN s.parking = 'unknown' THEN EXCLUDED.parking ELSE s.parking END,
    features           = COALESCE(s.features, EXCLUDED.features),
    features_source    = CASE WHEN s.features IS NULL THEN EXCLUDED.features_source ELSE s.features_source END,
    updated_at         = NOW();
  GET DIAGNOSTICS n = ROW_COUNT;
  RETURN n;
END $$;

REVOKE EXECUTE ON FUNCTION import_shrines(JSONB) FROM PUBLIC, anon, authenticated;

-- ============================================================
-- 管理者用（アプリの「申請の確認」画面から呼ぶ）
-- ============================================================
CREATE OR REPLACE FUNCTION is_admin() RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM admins WHERE user_id = auth.uid());
$$;

-- 申請を承認・却下する
--   add  を承認: shrine の内容（name, name_kana, prefecture, municipality, address, lat, lng）で shrines に追加
--               地図から申請（from_map）なら、申請した人の参拝記録を作る（参拝日＝申請日、「現地で記録」の印付き、非公開）
--   hide を承認: 対象の神社を status = 'hidden' にする
-- 戻り値は追加・非表示にした神社の id（却下は NULL）
CREATE OR REPLACE FUNCTION review_shrine_request(request_id UUID, approve BOOLEAN, shrine JSONB DEFAULT '{}')
RETURNS BIGINT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  req shrine_requests;
  target BIGINT;
BEGIN
  IF NOT is_admin() THEN
    RAISE EXCEPTION '管理者だけが実行できます' USING ERRCODE = '42501';
  END IF;
  SELECT * INTO req FROM shrine_requests WHERE id = request_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION '申請が見つかりません'; END IF;
  IF req.status <> 'pending' THEN RAISE EXCEPTION 'この申請は処理済みです'; END IF;

  IF approve AND req.kind = 'add' THEN
    INSERT INTO shrines (name, name_kana, prefecture, municipality, address, lat, lng)
    VALUES (
      COALESCE(NULLIF(btrim(shrine->>'name'), ''), req.name),
      NULLIF(btrim(shrine->>'name_kana'), ''),
      shrine->>'prefecture',
      NULLIF(btrim(shrine->>'municipality'), ''),
      NULLIF(btrim(shrine->>'address'), ''),
      COALESCE((shrine->>'lat')::DOUBLE PRECISION, req.lat),
      COALESCE((shrine->>'lng')::DOUBLE PRECISION, req.lng))
    RETURNING id INTO target;
    IF req.from_map THEN
      INSERT INTO records (user_id, shrine_id, visited_on, onsite, is_public)
      VALUES (req.user_id, target, (req.created_at AT TIME ZONE 'Asia/Tokyo')::DATE, TRUE, FALSE);
    END IF;
  ELSIF approve AND req.kind = 'hide' THEN
    UPDATE shrines SET status = 'hidden', updated_at = NOW() WHERE id = req.shrine_id;
    target := req.shrine_id;
  END IF;

  UPDATE shrine_requests SET
    status      = CASE WHEN approve THEN 'approved' ELSE 'rejected' END::request_status,
    shrine_id   = COALESCE(target, shrine_id),
    reviewed_at = NOW()
  WHERE id = request_id;
  RETURN target;
END $$;

REVOKE EXECUTE ON FUNCTION review_shrine_request(UUID, BOOLEAN, JSONB) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION review_shrine_request(UUID, BOOLEAN, JSONB) TO authenticated;

-- 情報提供の確認：いたずらを元に戻す・その人の情報提供と申請を止める
CREATE OR REPLACE FUNCTION is_edit_banned() RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM banned_editors WHERE user_id = auth.uid());
$$;

-- 情報提供を1件元に戻す（管理者）
--   同じ神社・同じ項目に後からの変更があるときは戻さない（新しい変更から順に戻す）
CREATE OR REPLACE FUNCTION revert_shrine_edit(edit_id UUID) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  e shrine_edits;
  s shrines;
BEGIN
  IF NOT is_admin() THEN
    RAISE EXCEPTION '管理者だけが実行できます' USING ERRCODE = '42501';
  END IF;
  SELECT * INTO e FROM shrine_edits WHERE id = edit_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION '情報提供が見つかりません'; END IF;
  IF e.reverted_at IS NOT NULL THEN RAISE EXCEPTION 'すでに元に戻しています'; END IF;
  IF e.old_value IS NULL THEN RAISE EXCEPTION '変更前の値が残っていないため戻せません（この機能を入れる前の変更です）'; END IF;
  IF EXISTS (SELECT 1 FROM shrine_edits
             WHERE shrine_id = e.shrine_id AND field = e.field AND reverted_at IS NULL AND created_at > e.created_at) THEN
    RAISE EXCEPTION 'この項目は後から変更されています。新しい変更から順に戻してください';
  END IF;

  -- 今の値に変更前の値を重ねたもの
  SELECT * INTO s FROM jsonb_populate_record(NULL::shrines,
    (SELECT to_jsonb(x) FROM shrines x WHERE x.id = e.shrine_id) || e.old_value);

  UPDATE shrines SET
    address = s.address, name_kana = s.name_kana, deities = s.deities, shrine_rank = s.shrine_rank,
    access_note = s.access_note, goshuin_note = s.goshuin_note,
    founded = s.founded, annual_festival = s.annual_festival, visiting_hours = s.visiting_hours, highlights = s.highlights,
    features = s.features, features_source = s.features_source,
    benefits = s.benefits, parking = s.parking, goshuin = s.goshuin,
    nearest_station = s.nearest_station, nearest_station_m = s.nearest_station_m,
    nearest_station_by_user = s.nearest_station_by_user,
    nearest_bus_stop = s.nearest_bus_stop, nearest_bus_stop_m = s.nearest_bus_stop_m,
    nearest_bus_stop_by_user = s.nearest_bus_stop_by_user,
    updated_at = NOW()
  WHERE id = e.shrine_id;

  UPDATE shrine_edits SET reverted_at = NOW() WHERE id = edit_id;
END $$;

-- あるユーザーの情報提供を新しい順にまとめて元に戻す（管理者）
-- 戻り値: { reverted: 戻した件数, skipped: 後から別の人が変更したなどで戻せなかった件数 }
CREATE OR REPLACE FUNCTION revert_user_edits(target UUID) RETURNS JSON
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  edit RECORD;
  reverted INTEGER := 0;
  skipped  INTEGER := 0;
BEGIN
  IF NOT is_admin() THEN
    RAISE EXCEPTION '管理者だけが実行できます' USING ERRCODE = '42501';
  END IF;
  FOR edit IN SELECT id FROM shrine_edits WHERE user_id = target AND reverted_at IS NULL ORDER BY created_at DESC LOOP
    BEGIN
      PERFORM revert_shrine_edit(edit.id);
      reverted := reverted + 1;
    EXCEPTION WHEN OTHERS THEN
      skipped := skipped + 1;
    END;
  END LOOP;
  RETURN json_build_object('reverted', reverted, 'skipped', skipped);
END $$;

-- 情報提供・申請を止める／止めるのをやめる（管理者）
CREATE OR REPLACE FUNCTION set_editor_banned(target UUID, banned BOOLEAN) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT is_admin() THEN
    RAISE EXCEPTION '管理者だけが実行できます' USING ERRCODE = '42501';
  END IF;
  IF banned THEN
    INSERT INTO banned_editors (user_id) VALUES (target) ON CONFLICT DO NOTHING;
  ELSE
    DELETE FROM banned_editors WHERE user_id = target;
  END IF;
END $$;

REVOKE EXECUTE ON FUNCTION revert_shrine_edit(UUID), revert_user_edits(UUID), set_editor_banned(UUID, BOOLEAN) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION revert_shrine_edit(UUID), revert_user_edits(UUID), set_editor_banned(UUID, BOOLEAN) TO authenticated;

-- ============================================================
-- 公開情報の読み取り（user_id は返さず、画面に要る列だけを返す）
--   他人の記録・写真・情報提供の履歴は、表を直接読めない（本人と管理者だけ）。この関数を通す
-- ============================================================

-- 表示する名前。「名前を出す」にしてニックネームがある人だけ。ほかは NULL
CREATE OR REPLACE FUNCTION display_name(target UUID) RETURNS TEXT
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT nickname FROM profiles WHERE user_id = target AND show_name AND nickname IS NOT NULL;
$$;

-- 神社の公開記録（新しい順）。author は表示する名前（NULL なら名前なし）
CREATE OR REPLACE FUNCTION get_public_records(target BIGINT, max_rows INT DEFAULT 20)
RETURNS TABLE (id UUID, visited_on DATE, emotion_level INT, public_memo TEXT, photos JSONB, author TEXT)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT r.id, r.visited_on, r.emotion_level, r.public_memo,
         COALESCE((SELECT jsonb_agg(jsonb_build_object('path', p.path, 'tag', p.tag) ORDER BY p.created_at, p.path)
                   FROM photos p WHERE p.record_id = r.id), '[]'::JSONB),
         display_name(r.user_id)
  FROM records r
  WHERE r.shrine_id = target AND r.is_public
  ORDER BY r.visited_on DESC, r.created_at DESC
  LIMIT LEAST(GREATEST(max_rows, 1), 100);
$$;

-- みんなの参拝：全国の公開記録（参拝日の新しい順）。写真は最初の1枚だけ。author は表示する名前（NULL なら名前なし）
CREATE OR REPLACE FUNCTION get_public_timeline(max_rows INT DEFAULT 30, skip INT DEFAULT 0)
RETURNS TABLE (id UUID, shrine_id BIGINT, shrine_name TEXT, prefecture TEXT, photo TEXT, author TEXT)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT r.id, s.id, s.name, s.prefecture,
         (SELECT p.path FROM photos p WHERE p.record_id = r.id ORDER BY p.created_at, p.path LIMIT 1),
         display_name(r.user_id)
  FROM records r JOIN shrines s ON s.id = r.shrine_id
  WHERE r.is_public AND s.status = 'active'
  ORDER BY r.visited_on DESC, r.created_at DESC, r.id
  LIMIT LEAST(GREATEST(max_rows, 1), 100) OFFSET GREATEST(skip, 0);
$$;

-- 神社の写真（公開記録のものだけ・新しい順）
CREATE OR REPLACE FUNCTION get_shrine_photos(target BIGINT, max_rows INT DEFAULT 200)
RETURNS TABLE (path TEXT, tag TEXT)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT p.path, p.tag
  FROM photos p JOIN records r ON r.id = p.record_id
  WHERE r.shrine_id = target AND r.is_public
  ORDER BY p.created_at DESC, p.path
  LIMIT LEAST(GREATEST(max_rows, 1), 500);
$$;

-- 神社の情報提供者（1人1行・最後に提供した順）。元に戻された変更は数えない
-- name が NULL の行は「名前を出していない人」
CREATE OR REPLACE FUNCTION get_shrine_contributors(target BIGINT)
RETURNS TABLE (name TEXT, edit_count INT, last_edited_at TIMESTAMPTZ)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT display_name(e.user_id), COUNT(*)::INT, MAX(e.created_at)
  FROM shrine_edits e
  WHERE e.shrine_id = target AND e.reverted_at IS NULL
  GROUP BY e.user_id
  ORDER BY MAX(e.created_at) DESC;
$$;

-- 写真のパスの先頭が「自分の記録のID」か（パスは <record_id>/<n>.jpg。以前は <user_id>/<record_id>/<n>.jpg）
CREATE OR REPLACE FUNCTION is_own_record_folder(object_name TEXT) RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM records
    WHERE id = CASE WHEN split_part(object_name, '/', 1) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
                    THEN split_part(object_name, '/', 1)::UUID END
      AND user_id = auth.uid());
$$;

-- 公開記録の写真か
CREATE OR REPLACE FUNCTION is_public_photo(object_name TEXT) RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM photos p JOIN records r ON r.id = p.record_id
                 WHERE p.path = object_name AND r.is_public);
$$;

-- ニックネームを初期化する（管理者）。不適切な名前を消す
CREATE OR REPLACE FUNCTION reset_nickname(target UUID) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT is_admin() THEN
    RAISE EXCEPTION '管理者だけが実行できます' USING ERRCODE = '42501';
  END IF;
  UPDATE profiles SET nickname = NULL, updated_at = NOW() WHERE user_id = target;
END $$;

-- 神社を完全に削除する（管理者）。その神社の参拝記録（みんなの分）・写真の行・非公開メモ・情報提供・申請も消える
-- 戻り値は消した記録の写真のパス（Storage のファイルはアプリが続けて消す）
CREATE OR REPLACE FUNCTION delete_shrine(target BIGINT) RETURNS TEXT[]
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  paths TEXT[];
BEGIN
  IF NOT is_admin() THEN
    RAISE EXCEPTION '管理者だけが実行できます' USING ERRCODE = '42501';
  END IF;
  PERFORM 1 FROM shrines WHERE id = target FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION '神社が見つかりません'; END IF;

  SELECT COALESCE(array_agg(p.path), '{}') INTO paths
  FROM photos p JOIN records r ON r.id = p.record_id WHERE r.shrine_id = target;
  DELETE FROM records WHERE shrine_id = target;   -- photos・record_private_notes は ON DELETE CASCADE
  DELETE FROM shrines WHERE id = target;          -- shrine_edits・shrine_requests は ON DELETE CASCADE
  RETURN paths;
END $$;

-- どの記録にも付いていない写真ファイルか（神社を消したあとに残ったファイル）
CREATE OR REPLACE FUNCTION is_orphan_photo(object_name TEXT) RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT NOT EXISTS (SELECT 1 FROM photos WHERE path = object_name);
$$;

REVOKE EXECUTE ON FUNCTION display_name(UUID) FROM PUBLIC, anon, authenticated;
GRANT  EXECUTE ON FUNCTION get_public_records(BIGINT, INT), get_public_timeline(INT, INT), get_shrine_photos(BIGINT, INT), get_shrine_contributors(BIGINT),
  is_own_record_folder(TEXT), is_public_photo(TEXT) TO anon, authenticated;
REVOKE EXECUTE ON FUNCTION reset_nickname(UUID) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION reset_nickname(UUID) TO authenticated;
REVOKE EXECUTE ON FUNCTION delete_shrine(BIGINT) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION delete_shrine(BIGINT) TO authenticated;
GRANT  EXECUTE ON FUNCTION is_orphan_photo(TEXT) TO authenticated;

-- ============================================================
-- Row Level Security
-- ============================================================
ALTER TABLE shrines              ENABLE ROW LEVEL SECURITY;
ALTER TABLE records              ENABLE ROW LEVEL SECURITY;
ALTER TABLE record_private_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE photos               ENABLE ROW LEVEL SECURITY;
ALTER TABLE shrine_edits         ENABLE ROW LEVEL SECURITY;
ALTER TABLE shrine_requests      ENABLE ROW LEVEL SECURITY;
ALTER TABLE guide_links          ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_meta             ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins               ENABLE ROW LEVEL SECURITY;
ALTER TABLE banned_editors       ENABLE ROW LEVEL SECURITY;
ALTER TABLE feedback             ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles             ENABLE ROW LEVEL SECURITY;
ALTER TABLE prayers              ENABLE ROW LEVEL SECURITY;

-- 神社：誰でも読める。書き込みは取り込み処理（service_role）とトリガーのみ
CREATE POLICY shrines_read ON shrines FOR SELECT USING (status = 'active');

-- 記録：公開記録は誰でも、自分の記録は本人が読める
-- 記録：表を読めるのは本人だけ。他人の公開記録は get_public_records() で（user_id を出さない）
CREATE POLICY records_read   ON records FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY records_insert ON records FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY records_update ON records FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY records_delete ON records FOR DELETE USING (auth.uid() = user_id);

-- 非公開メモ：本人のみ
CREATE POLICY notes_owner ON record_private_notes FOR ALL
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- 写真：表を読めるのは本人だけ。他人の公開記録の写真は get_public_records() / get_shrine_photos() で
CREATE POLICY photos_read ON photos FOR SELECT USING (auth.uid() = user_id);
-- 自分の記録にだけ付けられる
CREATE POLICY photos_insert ON photos FOR INSERT WITH CHECK (
  auth.uid() = user_id AND EXISTS (SELECT 1 FROM records r WHERE r.id = record_id AND r.user_id = auth.uid())
);
CREATE POLICY photos_delete ON photos FOR DELETE USING (auth.uid() = user_id);
-- 本人はタグだけ付け直せる（ほかの列は変えられない）
CREATE POLICY photos_update ON photos FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
REVOKE UPDATE ON photos FROM anon, authenticated;
GRANT UPDATE (tag) ON photos TO authenticated;

-- 情報提供：履歴を読めるのは管理者だけ（神社詳細の提供者の一覧は get_shrine_contributors() で）。ログインユーザーが追加できる（止められたユーザーを除く）
CREATE POLICY edits_read   ON shrine_edits FOR SELECT USING (is_admin());
CREATE POLICY edits_insert ON shrine_edits FOR INSERT WITH CHECK (auth.uid() = user_id AND NOT is_edit_banned());

-- 追加申請：本人と管理者が読める。承認・却下は review_shrine_request() で
CREATE POLICY requests_read   ON shrine_requests FOR SELECT USING (auth.uid() = user_id OR is_admin());
CREATE POLICY requests_insert ON shrine_requests FOR INSERT WITH CHECK (auth.uid() = user_id AND NOT is_edit_banned());

-- 管理者：自分が管理者かどうかだけ読める（登録は SQL Editor から）
CREATE POLICY admins_read_self ON admins FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY banned_editors_admin_read ON banned_editors FOR SELECT USING (is_admin());

-- ニックネーム：本人と管理者が読める。本人が登録・変更できる（情報提供を止められたユーザーを除く）
CREATE POLICY profiles_read   ON profiles FOR SELECT USING (auth.uid() = user_id OR is_admin());
CREATE POLICY profiles_insert ON profiles FOR INSERT WITH CHECK (auth.uid() = user_id AND NOT is_edit_banned());
CREATE POLICY profiles_update ON profiles FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id AND NOT is_edit_banned());

-- 神社でお祈りしたいこと：本人のみ
CREATE POLICY prayers_owner ON prayers FOR ALL
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ご意見・ご要望：ログインユーザーが送れる（止められたユーザーを除く）。読む・対応済みにするのは管理者だけ
CREATE POLICY feedback_insert ON feedback FOR INSERT WITH CHECK (auth.uid() = user_id AND NOT is_edit_banned());
CREATE POLICY feedback_admin_read   ON feedback FOR SELECT USING (is_admin());
CREATE POLICY feedback_admin_update ON feedback FOR UPDATE USING (is_admin()) WITH CHECK (is_admin());

-- 手引きリンク・設定値：誰でも読める（編集はダッシュボードから）
-- 神社一覧ファイルの版は、管理者がアプリから一覧を作り直したときにも更新する
CREATE POLICY guide_links_read ON guide_links FOR SELECT USING (is_active);
CREATE POLICY app_meta_read    ON app_meta    FOR SELECT USING (TRUE);
CREATE POLICY app_meta_admin_update ON app_meta FOR UPDATE
  USING (key = 'shrine_index_version' AND is_admin()) WITH CHECK (key = 'shrine_index_version' AND is_admin());

-- ============================================================
-- Storage
-- ============================================================
-- photos      : 非公開バケット。パスは <record_id>/<n>.jpg（以前は <user_id>/<record_id>/<n>.jpg）。署名付きURLで表示
-- public-data : 公開バケット。shrines-index.<version>.json.gz を置く（取り込み処理か、アプリの管理者画面がアップロード）
INSERT INTO storage.buckets (id, name, public) VALUES ('photos', 'photos', FALSE), ('public-data', 'public-data', TRUE)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY photos_obj_insert ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'photos' AND ((storage.foldername(name))[1] = auth.uid()::TEXT OR public.is_own_record_folder(name)));

CREATE POLICY photos_obj_delete ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'photos' AND ((storage.foldername(name))[1] = auth.uid()::TEXT OR public.is_own_record_folder(name)));

-- 本人の写真、または公開記録の写真なら読める
CREATE POLICY photos_obj_read ON storage.objects FOR SELECT
  USING (bucket_id = 'photos' AND (
    (storage.foldername(name))[1] = auth.uid()::TEXT
    OR public.is_own_record_folder(name)
    OR public.is_public_photo(name)
  ));

-- 管理者は、どの記録にも付いていない写真ファイル（神社を削除したあとに残ったもの）を消せる（Storage の削除には読む権限も要る）
CREATE POLICY photos_obj_admin_orphan_read ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'photos' AND public.is_admin() AND public.is_orphan_photo(name));
CREATE POLICY photos_obj_admin_orphan_delete ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'photos' AND public.is_admin() AND public.is_orphan_photo(name));

-- 管理者は神社一覧ファイルを置ける（毎回新しい名前なので上書きはしない）
CREATE POLICY public_data_admin_insert ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'public-data' AND name LIKE 'shrines-index.%' AND public.is_admin());
CREATE POLICY public_data_admin_read ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'public-data' AND public.is_admin());
